version: '3.7'
services:
  jormungandr:
    image: arct3r/jormungandr:0.8.18
    deploy:
      replicas: 1
    # restart_policy:
      # condition: any
    ### deprecated
    ### container_name: node01
    ###	
    ports:
      # - "3001:3001"
      # - "3100:3100"
      - published: 3002
        target: 3002
        protocol: tcp
        mode: host
      # - published: 3100
        # target: 3100
        # protocol: tcp
        # mode: host
    environment:
      - POOLTOOL_USER_ID=89c7bd70-45e4-4c53-877e-4de37f6d22d8
      # jormanager.pooltool.poolId=fb354577be37b9e98092d897f3f156530b6961438dc425feafb5aea4971aa662
    volumes:
      - /home/des_hawes/srv/srv02:/srv
    deploy:
      placement:
        constraints: [node.hostname == instance-2]