on: push


name: Test Docker Build

jobs:
  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Docker image
        run: .github/tests/00_docker-build.sh ${GITHUB_REF##*/}
      - name: Test 
      